name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: List and Read file
              run: |
                echo "My first Github Actions Job"
                ls -ltra
                cat README.md